# Generated by Django 6.0.5 on 2026-05-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
