# Generated by Django 6.0 on 2026-09-05 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['review', 'is_helpful'], name='products_re_review__38c5a4_idx'),
        ),
    ]
