# Generated by Django 6.0.5 on 2026-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='deliverycharge',
            unique_together={('delivery_area',)},
        ),
        migrations.AddIndex(
            model_name='deliverycharge',
            index=models.Index(fields=['delivery_area'], name='orders_deli_deliver_0b312e_idx'),
        ),
    ]
