# Generated by Django 6.0.5 on 2026-05-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_product_name_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='subtotal',
        ),
    ]
