# Generated by Django 6.0 on 2026-07-03 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartnerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='orders.deliverypartnerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['delivery_partner'], name='orders_deli_deliver_e98ede_idx')],
            },
        ),
    ]
