# Generated by Django 6.0 on 2026-07-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_deliverypartnerlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='deliverypartnerlocation',
            name='orders_deli_deliver_e98ede_idx',
        ),
        migrations.AddField(
            model_name='orderlivelocation',
            name='delivery_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_locations', to='orders.deliverypartnerprofile'),
        ),
        migrations.AddField(
            model_name='orderlivelocation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='orders.order'),
        ),
        migrations.RemoveField(
            model_name='deliverypartnerlocation',
            name='delivery_partner',
        ),
        migrations.AddIndex(
            model_name='orderlivelocation',
            index=models.Index(fields=['order'], name='orders_orde_order_i_28b2de_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlivelocation',
            index=models.Index(fields=['delivery_partner'], name='orders_orde_deliver_9e75d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlivelocation',
            index=models.Index(fields=['updated_at'], name='orders_orde_updated_300d23_idx'),
        ),
        migrations.DeleteModel(
            name='DeliveryPartnerLocation',
        ),
    ]
