# Generated by Django 6.0 on 2026-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_latitude_alter_order_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
