# Generated by Django 6.0 on 2026-09-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_latitude_alter_order_longitude'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='orders_addr_user_id_fd65f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_5d347b_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_product_32ff41_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlivelocation',
            name='orders_orde_order_i_28b2de_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderlivelocation',
            name='orders_orde_deliver_9e75d9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='deliverycharge',
            unique_together=set(),
        ),
    ]
