# Generated by Django 6.0.5 on 2026-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='info',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_delivery_partner',
            field=models.BooleanField(default=False),
        ),
    ]
