# Generated by Django 6.0.5 on 2026-05-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_usernam_a8ad03_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_is_staf_3b7c79_idx',
        ),
    ]
